### ISSUE TITLE
Add a media query to add left-right padding to nav-bar items for small screens

### ISSUE THREAD

**Issue by alexander-yord** [alexander-yord/lex-front-end#11]
The body element is with max width of 800px, and on larger screens, the lex icon aligns well with the body. However, we need a media query to add left-right padding to the item (the CSS selector can directly specify the id of the element (which would need to be added as well)). Check general/headers.css.

**Comment by abitsalihu** [comment]
Hey @alexander-yord, I would like to work on this issue.

**Comment by alexander-yord** [comment]
@abitsalihu Hi there, I added a slightly more detailed description. Let me know if you need help. The current version is hosted on [http://79.100.219.84:8008](http://79.100.219.84:8008)
